[tool.blue]
line-length = 800000000
# NB: Keep in sync with tox.ini.
target-version = ['py36', 'py37', 'py38', 'py39', 'py310', 'py311'] #, 'py312'

[tool.pytest.ini_options]
markers = """
    allow_cq: allow tests in the CQ. Should be used when necessarily!
"""
